#!/usr/bin/env ruby

# Set up environment
ENV['PATH'] = "#{ENV['HOME']}/.rbenv/shims:#{ENV['PATH']}"

require 'minitest/autorun'

puts "\n" + "="*60
puts "Running all Scriptorium tests..."
puts "="*60

# Load all test files
require_relative 'repo/unit'
require_relative 'post/unit'
require_relative 'banner_svg/unit'
require_relative 'integration/integration_test'
require_relative 'core/unit' # Tests core helper methods

puts "\n" + "="*60
puts "All tests completed!"
puts "="*60 + "\n"
