#!/usr/bin/env ruby

# Set up environment
ENV['PATH'] = "#{ENV['HOME']}/.rbenv/shims:#{ENV['PATH']}"

require 'minitest/autorun'

puts "\n" + "="*60
puts "Running all Scriptorium tests..."
puts "="*60

# Load all test files
require_relative 'unit/repo'
require_relative 'unit/post'
require_relative 'unit/view'
require_relative 'banner_svg/unit'
require_relative 'integration/integration_test'
require_relative 'unit/core' # Tests core helper methods

puts "\n" + "="*60
puts "All tests completed!"
puts "="*60 + "\n"
