#!/usr/bin/env ruby

# Set up environment
ENV['PATH'] = "#{ENV['HOME']}/.rbenv/shims:#{ENV['PATH']}"

require 'minitest/autorun'

puts "\n" + "="*60
puts "Running all Scriptorium tests..."
puts "="*60

# Initialize global to track which test files have printed their name
$printed_files = []

# Automatically find and load all test files
test_files = %w[
  unit/api.rb
  unit/post.rb
  unit/repo.rb
  unit/view.rb
  unit/widgets.rb
  unit/read_commented_file_test.rb
  unit/asset_management.rb
  unit/gem_asset_management.rb
  unit/reddit_test.rb
  unit/clipboard_test.rb
  unit/deploy_test.rb
  unit/deploy_config_test.rb
  unit/permalink_copy_test.rb
  unit/post_state_helpers_test.rb
  unit/edit_post_test.rb
  unit/contract_test.rb
  unit/social_test.rb
  unit/livetext_compatibility.rb
  unit/livetext_basic.rb
  unit/syntax_highlighting.rb
  banner_svg/simple_helpers.rb
  banner_svg/unit.rb
  integration/integration_test.rb
  livetext_plugin_test.rb
  unit/core.rb
  unit/post_index_config_test.rb
  unit/parse_cmd_test.rb
  unit/backup_test.rb
  unit/theme_management_test.rb
  ed_test.rb
  tui_integration_test.rb
  tui_editor_integration_test.rb
  web_integration_test.rb
  web_workflow_test.rb
]


# Load all test files
test_files.each do |file|
  require_relative file
rescue => e
  puts "Error loading #{file}: #{e.message}"
end
