#!/usr/bin/env ruby

require 'runeblog'

# If gem is not installed, hotfix is meaningless.
begin
  entry = `gem list | grep runeblog`
  entry.nil? && abort("Can't hotfix: Gem is not installed")
rescue
  abort "Can't verify hotfix: Can't run 'gem' command."
end

lib = RuneBlog::Path

puts lib

files = Dir["lib/*.rb"]
bad = false
files.each do |f|
  msg = `ruby -c #{f} 2>&1`
  if msg !~ /Syntax OK/
    bad = true
    err = msg.split("\n")[0]
    puts "#{err}   (Press return to edit)"
    STDIN.gets
    file, line, * = err.split(":")
    system("vi #{file} +#{line}")
  end
end

abort "\nYou'll need to re-run\n " if bad


# Let's go!

system("livetext -i lib/liveblog.rb")

system("cp -r lib/* #{lib}/")

rc = system("cp -R empty_view #{lib}/..")
puts "Error copying empty_view!" unless rc

rc = system("cp -R data/* #{lib}/../data")
puts "Error copying data dir!" unless rc

# puts "...finished"

# Exception in dir structure
cmd = "cp bin/* #{lib.sub(/lib$/, "bin/")}"
# puts cmd
system(cmd)

# puts

