#!/usr/bin/env ruby

require 'runeblog'

lib = RuneBlog::Path

files = Dir["lib/*.rb"]
bad = false
files.each do |f|
puts "File = #{f}"
  system("ruby -c #{f} 2>&1")
exit
  msg = `ruby -c #{f} 2>&1`
p msg
  if msg !~ /Syntax OK/
    bad = true
    err = msg.split("\n")[0]
    puts "#{err}   (Press return to edit)"
    STDIN.gets
    file, line, * = err.split(":")
    system("vi #{file} +#{line}")
  end
end

abort "\nYou'll need to re-run\n " if bad


# Let's go!

system("livetext -i lib/liveblog.rb")

system("cp lib/* #{lib}/")

rc = system("cp -R empty_view #{lib}/..")
puts "Error copying empty_view!" unless rc

# puts "...finished"

# Exception in dir structure
cmd = "cp bin/* #{lib.sub(/lib$/, "bin/")}"
# puts cmd
system(cmd)

# puts

